/* nsDataSoapProxy.h
   Generated by gSOAP 2.8.28 from eoddatawebservice.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef nsDataSoapProxy_H
#define nsDataSoapProxy_H
#include "nsH.h"

namespace ns {

class SOAP_CMAC DataSoapProxy
{ public:
	struct soap *soap;
	bool soap_own;
	/// Endpoint URL of service 'DataSoapProxy' (change as needed)
	const char *soap_endpoint;
	/// Variables globally declared in eoddatawebservice.h (non-static)
	/// Constructor
	DataSoapProxy();
	/// Copy constructor
	DataSoapProxy(const DataSoapProxy& rhs);
	/// Constructor to use/share an engine state
	DataSoapProxy(struct soap*);
	/// Constructor with endpoint URL
	DataSoapProxy(const char *url);
	/// Constructor with engine input+output mode control
	DataSoapProxy(soap_mode iomode);
	/// Constructor with URL and input+output mode control
	DataSoapProxy(const char *url, soap_mode iomode);
	/// Constructor with engine input and output mode control
	DataSoapProxy(soap_mode imode, soap_mode omode);
	/// Destructor deletes non-shared engine context only (use destroy() to delete deserialized data)
	virtual	~DataSoapProxy();
	/// Initializer used by constructors
	virtual	void DataSoapProxy_init(soap_mode imode, soap_mode omode);
	/// Create a new copy
	virtual	DataSoapProxy *copy() SOAP_PURE_VIRTUAL;
	/// Copy assignment
	DataSoapProxy& operator=(const DataSoapProxy&);
	/// Delete all deserialized data (with soap_destroy and soap_end)
	virtual	void destroy();
	/// Delete all deserialized data and reset to default
	virtual	void reset();
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Get SOAP Fault structure (NULL when absent)
	virtual	const SOAP_ENV__Fault *soap_fault();
	/// Get SOAP Fault string (NULL when absent)
	virtual	const char *soap_fault_string();
	/// Get SOAP Fault detail as string (NULL when absent)
	virtual	const char *soap_fault_detail();
	/// Close connection (normally automatic, except for send_X ops)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif

	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2(_ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response) { return this->Login2(NULL, NULL, ns1__Login2, ns1__Login2Response); }
	virtual	int Login2(const char *endpoint, const char *soap_action, _ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response);

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership(_ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse) { return this->Membership(NULL, NULL, ns1__Membership, ns1__MembershipResponse); }
	virtual	int Membership(const char *endpoint, const char *soap_action, _ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse);

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList(_ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse) { return this->ExchangeList(NULL, NULL, ns1__ExchangeList, ns1__ExchangeListResponse); }
	virtual	int ExchangeList(const char *endpoint, const char *soap_action, _ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse);

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet(_ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse) { return this->ExchangeGet(NULL, NULL, ns1__ExchangeGet, ns1__ExchangeGetResponse); }
	virtual	int ExchangeGet(const char *endpoint, const char *soap_action, _ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse);

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList(_ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse) { return this->SymbolList(NULL, NULL, ns1__SymbolList, ns1__SymbolListResponse); }
	virtual	int SymbolList(const char *endpoint, const char *soap_action, _ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse);

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2(_ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response) { return this->SymbolList2(NULL, NULL, ns1__SymbolList2, ns1__SymbolList2Response); }
	virtual	int SymbolList2(const char *endpoint, const char *soap_action, _ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response);

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet(_ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse) { return this->QuoteGet(NULL, NULL, ns1__QuoteGet, ns1__QuoteGetResponse); }
	virtual	int QuoteGet(const char *endpoint, const char *soap_action, _ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse);

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2(_ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response) { return this->QuoteList2(NULL, NULL, ns1__QuoteList2, ns1__QuoteList2Response); }
	virtual	int QuoteList2(const char *endpoint, const char *soap_action, _ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response);

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet(_ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse) { return this->SymbolGet(NULL, NULL, ns1__SymbolGet, ns1__SymbolGetResponse); }
	virtual	int SymbolGet(const char *endpoint, const char *soap_action, _ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse);

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList(_ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse) { return this->QuoteList(NULL, NULL, ns1__QuoteList, ns1__QuoteListResponse); }
	virtual	int QuoteList(const char *endpoint, const char *soap_action, _ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse);

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList(_ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse) { return this->NewsList(NULL, NULL, ns1__NewsList, ns1__NewsListResponse); }
	virtual	int NewsList(const char *endpoint, const char *soap_action, _ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse);

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol(_ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse) { return this->NewsListBySymbol(NULL, NULL, ns1__NewsListBySymbol, ns1__NewsListBySymbolResponse); }
	virtual	int NewsListBySymbol(const char *endpoint, const char *soap_action, _ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse);

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList(_ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse) { return this->FundamentalList(NULL, NULL, ns1__FundamentalList, ns1__FundamentalListResponse); }
	virtual	int FundamentalList(const char *endpoint, const char *soap_action, _ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse);

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList(_ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse) { return this->TechnicalList(NULL, NULL, ns1__TechnicalList, ns1__TechnicalListResponse); }
	virtual	int TechnicalList(const char *endpoint, const char *soap_action, _ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse);

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate(_ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse) { return this->QuoteListByDate(NULL, NULL, ns1__QuoteListByDate, ns1__QuoteListByDateResponse); }
	virtual	int QuoteListByDate(const char *endpoint, const char *soap_action, _ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse);

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2(_ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response) { return this->QuoteListByDate2(NULL, NULL, ns1__QuoteListByDate2, ns1__QuoteListByDate2Response); }
	virtual	int QuoteListByDate2(const char *endpoint, const char *soap_action, _ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response);

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory(_ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse) { return this->SymbolHistory(NULL, NULL, ns1__SymbolHistory, ns1__SymbolHistoryResponse); }
	virtual	int SymbolHistory(const char *endpoint, const char *soap_action, _ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse);

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains(_ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse) { return this->Top10Gains(NULL, NULL, ns1__Top10Gains, ns1__Top10GainsResponse); }
	virtual	int Top10Gains(const char *endpoint, const char *soap_action, _ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse);

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses(_ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse) { return this->Top10Losses(NULL, NULL, ns1__Top10Losses, ns1__Top10LossesResponse); }
	virtual	int Top10Losses(const char *endpoint, const char *soap_action, _ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse);

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart(_ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse) { return this->SymbolChart(NULL, NULL, ns1__SymbolChart, ns1__SymbolChartResponse); }
	virtual	int SymbolChart(const char *endpoint, const char *soap_action, _ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse);

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths(_ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse) { return this->ExchangeMonths(NULL, NULL, ns1__ExchangeMonths, ns1__ExchangeMonthsResponse); }
	virtual	int ExchangeMonths(const char *endpoint, const char *soap_action, _ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse);

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange(_ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse) { return this->SplitListByExchange(NULL, NULL, ns1__SplitListByExchange, ns1__SplitListByExchangeResponse); }
	virtual	int SplitListByExchange(const char *endpoint, const char *soap_action, _ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse);

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol(_ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse) { return this->SplitListBySymbol(NULL, NULL, ns1__SplitListBySymbol, ns1__SplitListBySymbolResponse); }
	virtual	int SplitListBySymbol(const char *endpoint, const char *soap_action, _ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse);

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList(_ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse) { return this->CountryList(NULL, NULL, ns1__CountryList, ns1__CountryListResponse); }
	virtual	int CountryList(const char *endpoint, const char *soap_action, _ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse);

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod(_ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse) { return this->SymbolHistoryPeriod(NULL, NULL, ns1__SymbolHistoryPeriod, ns1__SymbolHistoryPeriodResponse); }
	virtual	int SymbolHistoryPeriod(const char *endpoint, const char *soap_action, _ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse);

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange(_ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse) { return this->SymbolHistoryPeriodByDateRange(NULL, NULL, ns1__SymbolHistoryPeriodByDateRange, ns1__SymbolHistoryPeriodByDateRangeResponse); }
	virtual	int SymbolHistoryPeriodByDateRange(const char *endpoint, const char *soap_action, _ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse);

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod(_ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse) { return this->QuoteListByDatePeriod(NULL, NULL, ns1__QuoteListByDatePeriod, ns1__QuoteListByDatePeriodResponse); }
	virtual	int QuoteListByDatePeriod(const char *endpoint, const char *soap_action, _ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse);

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2(_ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response) { return this->QuoteListByDatePeriod2(NULL, NULL, ns1__QuoteListByDatePeriod2, ns1__QuoteListByDatePeriod2Response); }
	virtual	int QuoteListByDatePeriod2(const char *endpoint, const char *soap_action, _ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response);

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange(_ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse) { return this->SymbolChangesByExchange(NULL, NULL, ns1__SymbolChangesByExchange, ns1__SymbolChangesByExchangeResponse); }
	virtual	int SymbolChangesByExchange(const char *endpoint, const char *soap_action, _ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse);

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion(_ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse) { return this->DataClientLatestVersion(NULL, NULL, ns1__DataClientLatestVersion, ns1__DataClientLatestVersionResponse); }
	virtual	int DataClientLatestVersion(const char *endpoint, const char *soap_action, _ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse);

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats(_ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse) { return this->DataFormats(NULL, NULL, ns1__DataFormats, ns1__DataFormatsResponse); }
	virtual	int DataFormats(const char *endpoint, const char *soap_action, _ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse);

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat(_ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse) { return this->UpdateDataFormat(NULL, NULL, ns1__UpdateDataFormat, ns1__UpdateDataFormatResponse); }
	virtual	int UpdateDataFormat(const char *endpoint, const char *soap_action, _ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse);

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess(_ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse) { return this->ValidateAccess(NULL, NULL, ns1__ValidateAccess, ns1__ValidateAccessResponse); }
	virtual	int ValidateAccess(const char *endpoint, const char *soap_action, _ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login_(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) { return this->Login_(NULL, NULL, ns1__Login, ns1__LoginResponse); }
	virtual	int Login_(const char *endpoint, const char *soap_action, _ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse);

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2_(_ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response) { return this->Login2_(NULL, NULL, ns1__Login2, ns1__Login2Response); }
	virtual	int Login2_(const char *endpoint, const char *soap_action, _ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response);

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership_(_ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse) { return this->Membership_(NULL, NULL, ns1__Membership, ns1__MembershipResponse); }
	virtual	int Membership_(const char *endpoint, const char *soap_action, _ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse);

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList_(_ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse) { return this->ExchangeList_(NULL, NULL, ns1__ExchangeList, ns1__ExchangeListResponse); }
	virtual	int ExchangeList_(const char *endpoint, const char *soap_action, _ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse);

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet_(_ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse) { return this->ExchangeGet_(NULL, NULL, ns1__ExchangeGet, ns1__ExchangeGetResponse); }
	virtual	int ExchangeGet_(const char *endpoint, const char *soap_action, _ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse);

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList_(_ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse) { return this->SymbolList_(NULL, NULL, ns1__SymbolList, ns1__SymbolListResponse); }
	virtual	int SymbolList_(const char *endpoint, const char *soap_action, _ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse);

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2_(_ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response) { return this->SymbolList2_(NULL, NULL, ns1__SymbolList2, ns1__SymbolList2Response); }
	virtual	int SymbolList2_(const char *endpoint, const char *soap_action, _ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response);

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet_(_ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse) { return this->QuoteGet_(NULL, NULL, ns1__QuoteGet, ns1__QuoteGetResponse); }
	virtual	int QuoteGet_(const char *endpoint, const char *soap_action, _ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse);

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2_(_ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response) { return this->QuoteList2_(NULL, NULL, ns1__QuoteList2, ns1__QuoteList2Response); }
	virtual	int QuoteList2_(const char *endpoint, const char *soap_action, _ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response);

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet_(_ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse) { return this->SymbolGet_(NULL, NULL, ns1__SymbolGet, ns1__SymbolGetResponse); }
	virtual	int SymbolGet_(const char *endpoint, const char *soap_action, _ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse);

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList_(_ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse) { return this->QuoteList_(NULL, NULL, ns1__QuoteList, ns1__QuoteListResponse); }
	virtual	int QuoteList_(const char *endpoint, const char *soap_action, _ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse);

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList_(_ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse) { return this->NewsList_(NULL, NULL, ns1__NewsList, ns1__NewsListResponse); }
	virtual	int NewsList_(const char *endpoint, const char *soap_action, _ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse);

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol_(_ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse) { return this->NewsListBySymbol_(NULL, NULL, ns1__NewsListBySymbol, ns1__NewsListBySymbolResponse); }
	virtual	int NewsListBySymbol_(const char *endpoint, const char *soap_action, _ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse);

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList_(_ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse) { return this->FundamentalList_(NULL, NULL, ns1__FundamentalList, ns1__FundamentalListResponse); }
	virtual	int FundamentalList_(const char *endpoint, const char *soap_action, _ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse);

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList_(_ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse) { return this->TechnicalList_(NULL, NULL, ns1__TechnicalList, ns1__TechnicalListResponse); }
	virtual	int TechnicalList_(const char *endpoint, const char *soap_action, _ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse);

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate_(_ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse) { return this->QuoteListByDate_(NULL, NULL, ns1__QuoteListByDate, ns1__QuoteListByDateResponse); }
	virtual	int QuoteListByDate_(const char *endpoint, const char *soap_action, _ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse);

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2_(_ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response) { return this->QuoteListByDate2_(NULL, NULL, ns1__QuoteListByDate2, ns1__QuoteListByDate2Response); }
	virtual	int QuoteListByDate2_(const char *endpoint, const char *soap_action, _ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response);

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory_(_ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse) { return this->SymbolHistory_(NULL, NULL, ns1__SymbolHistory, ns1__SymbolHistoryResponse); }
	virtual	int SymbolHistory_(const char *endpoint, const char *soap_action, _ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse);

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains_(_ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse) { return this->Top10Gains_(NULL, NULL, ns1__Top10Gains, ns1__Top10GainsResponse); }
	virtual	int Top10Gains_(const char *endpoint, const char *soap_action, _ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse);

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses_(_ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse) { return this->Top10Losses_(NULL, NULL, ns1__Top10Losses, ns1__Top10LossesResponse); }
	virtual	int Top10Losses_(const char *endpoint, const char *soap_action, _ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse);

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart_(_ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse) { return this->SymbolChart_(NULL, NULL, ns1__SymbolChart, ns1__SymbolChartResponse); }
	virtual	int SymbolChart_(const char *endpoint, const char *soap_action, _ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse);

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths_(_ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse) { return this->ExchangeMonths_(NULL, NULL, ns1__ExchangeMonths, ns1__ExchangeMonthsResponse); }
	virtual	int ExchangeMonths_(const char *endpoint, const char *soap_action, _ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse);

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange_(_ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse) { return this->SplitListByExchange_(NULL, NULL, ns1__SplitListByExchange, ns1__SplitListByExchangeResponse); }
	virtual	int SplitListByExchange_(const char *endpoint, const char *soap_action, _ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse);

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol_(_ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse) { return this->SplitListBySymbol_(NULL, NULL, ns1__SplitListBySymbol, ns1__SplitListBySymbolResponse); }
	virtual	int SplitListBySymbol_(const char *endpoint, const char *soap_action, _ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse);

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList_(_ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse) { return this->CountryList_(NULL, NULL, ns1__CountryList, ns1__CountryListResponse); }
	virtual	int CountryList_(const char *endpoint, const char *soap_action, _ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse);

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod_(_ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse) { return this->SymbolHistoryPeriod_(NULL, NULL, ns1__SymbolHistoryPeriod, ns1__SymbolHistoryPeriodResponse); }
	virtual	int SymbolHistoryPeriod_(const char *endpoint, const char *soap_action, _ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse);

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange_(_ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse) { return this->SymbolHistoryPeriodByDateRange_(NULL, NULL, ns1__SymbolHistoryPeriodByDateRange, ns1__SymbolHistoryPeriodByDateRangeResponse); }
	virtual	int SymbolHistoryPeriodByDateRange_(const char *endpoint, const char *soap_action, _ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse);

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod_(_ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse) { return this->QuoteListByDatePeriod_(NULL, NULL, ns1__QuoteListByDatePeriod, ns1__QuoteListByDatePeriodResponse); }
	virtual	int QuoteListByDatePeriod_(const char *endpoint, const char *soap_action, _ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse);

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2_(_ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response) { return this->QuoteListByDatePeriod2_(NULL, NULL, ns1__QuoteListByDatePeriod2, ns1__QuoteListByDatePeriod2Response); }
	virtual	int QuoteListByDatePeriod2_(const char *endpoint, const char *soap_action, _ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response);

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange_(_ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse) { return this->SymbolChangesByExchange_(NULL, NULL, ns1__SymbolChangesByExchange, ns1__SymbolChangesByExchangeResponse); }
	virtual	int SymbolChangesByExchange_(const char *endpoint, const char *soap_action, _ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse);

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion_(_ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse) { return this->DataClientLatestVersion_(NULL, NULL, ns1__DataClientLatestVersion, ns1__DataClientLatestVersionResponse); }
	virtual	int DataClientLatestVersion_(const char *endpoint, const char *soap_action, _ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse);

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats_(_ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse) { return this->DataFormats_(NULL, NULL, ns1__DataFormats, ns1__DataFormatsResponse); }
	virtual	int DataFormats_(const char *endpoint, const char *soap_action, _ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse);

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat_(_ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse) { return this->UpdateDataFormat_(NULL, NULL, ns1__UpdateDataFormat, ns1__UpdateDataFormatResponse); }
	virtual	int UpdateDataFormat_(const char *endpoint, const char *soap_action, _ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse);

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess_(_ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse) { return this->ValidateAccess_(NULL, NULL, ns1__ValidateAccess, ns1__ValidateAccessResponse); }
	virtual	int ValidateAccess_(const char *endpoint, const char *soap_action, _ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse);

	/// Web service operation 'LoginResponse' (returns error code or SOAP_OK)
	virtual	int LoginResponse__(ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) { return this->LoginResponse__(NULL, NULL, ns1__LOGINRESPONSE_); }
	virtual	int LoginResponse__(const char *endpoint, const char *soap_action, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_);

	/// Web service operation 'Login2Response' (returns error code or SOAP_OK)
	virtual	int Login2Response__(ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) { return this->Login2Response__(NULL, NULL, ns1__LOGINRESPONSE_); }
	virtual	int Login2Response__(const char *endpoint, const char *soap_action, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_);

	/// Web service operation 'MembershipResponse' (returns error code or SOAP_OK)
	virtual	int MembershipResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->MembershipResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int MembershipResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeListResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int ExchangeListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeGetResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeGetResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int ExchangeGetResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolListResponse' (returns error code or SOAP_OK)
	virtual	int SymbolListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolList2Response' (returns error code or SOAP_OK)
	virtual	int SymbolList2Response__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolList2Response__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolList2Response__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteGetResponse' (returns error code or SOAP_OK)
	virtual	int QuoteGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteGetResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteGetResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteList2Response' (returns error code or SOAP_OK)
	virtual	int QuoteList2Response__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteList2Response__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteList2Response__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolGetResponse' (returns error code or SOAP_OK)
	virtual	int SymbolGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolGetResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolGetResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'NewsListResponse' (returns error code or SOAP_OK)
	virtual	int NewsListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->NewsListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int NewsListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'NewsListBySymbolResponse' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbolResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->NewsListBySymbolResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int NewsListBySymbolResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'FundamentalListResponse' (returns error code or SOAP_OK)
	virtual	int FundamentalListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->FundamentalListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int FundamentalListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'TechnicalListResponse' (returns error code or SOAP_OK)
	virtual	int TechnicalListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->TechnicalListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int TechnicalListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDateResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListByDateResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDateResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteListByDateResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDate2Response' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2Response__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDate2Response__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteListByDate2Response__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistoryResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistoryResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolHistoryResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'Top10GainsResponse' (returns error code or SOAP_OK)
	virtual	int Top10GainsResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->Top10GainsResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int Top10GainsResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'Top10LossesResponse' (returns error code or SOAP_OK)
	virtual	int Top10LossesResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->Top10LossesResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int Top10LossesResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolChartResponse' (returns error code or SOAP_OK)
	virtual	int SymbolChartResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolChartResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolChartResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeMonthsResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeMonthsResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeMonthsResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int ExchangeMonthsResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SplitListByExchangeResponse' (returns error code or SOAP_OK)
	virtual	int SplitListByExchangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SplitListByExchangeResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SplitListByExchangeResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SplitListBySymbolResponse' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbolResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SplitListBySymbolResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SplitListBySymbolResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'CountryListResponse' (returns error code or SOAP_OK)
	virtual	int CountryListResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->CountryListResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int CountryListResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistoryPeriodResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistoryPeriodResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolHistoryPeriodResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistoryPeriodByDateRangeResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistoryPeriodByDateRangeResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolHistoryPeriodByDateRangeResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDatePeriodResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriodResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDatePeriodResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteListByDatePeriodResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDatePeriod2Response' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2Response__(ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDatePeriod2Response__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int QuoteListByDatePeriod2Response__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolChangesByExchangeResponse' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolChangesByExchangeResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int SymbolChangesByExchangeResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'DataClientLatestVersionResponse' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersionResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->DataClientLatestVersionResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int DataClientLatestVersionResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'DataFormatsResponse' (returns error code or SOAP_OK)
	virtual	int DataFormatsResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->DataFormatsResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int DataFormatsResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'UpdateDataFormatResponse' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormatResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->UpdateDataFormatResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int UpdateDataFormatResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ValidateAccessResponse' (returns error code or SOAP_OK)
	virtual	int ValidateAccessResponse__(ns1__RESPONSE &ns1__RESPONSE_) { return this->ValidateAccessResponse__(NULL, NULL, ns1__RESPONSE_); }
	virtual	int ValidateAccessResponse__(const char *endpoint, const char *soap_action, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login___(std::string Username, std::string Password, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) { return this->Login___(NULL, NULL, Username, Password, ns1__LOGINRESPONSE_); }
	virtual	int Login___(const char *endpoint, const char *soap_action, std::string Username, std::string Password, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_);

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2___(std::string Username, std::string Password, std::string Version, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) { return this->Login2___(NULL, NULL, Username, Password, Version, ns1__LOGINRESPONSE_); }
	virtual	int Login2___(const char *endpoint, const char *soap_action, std::string Username, std::string Password, std::string Version, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_);

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) { return this->Membership___(NULL, NULL, Token, ns1__RESPONSE_); }
	virtual	int Membership___(const char *endpoint, const char *soap_action, std::string Token, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeList___(NULL, NULL, Token, ns1__RESPONSE_); }
	virtual	int ExchangeList___(const char *endpoint, const char *soap_action, std::string Token, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeGet___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int ExchangeGet___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolList___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int SymbolList___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolList2___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int SymbolList2___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteGet___(NULL, NULL, Token, Exchange, Symbol, ns1__RESPONSE_); }
	virtual	int QuoteGet___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2___(std::string Token, std::string Exchange, std::string Symbols, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteList2___(NULL, NULL, Token, Exchange, Symbols, ns1__RESPONSE_); }
	virtual	int QuoteList2___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbols, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolGet___(NULL, NULL, Token, Exchange, Symbol, ns1__RESPONSE_); }
	virtual	int SymbolGet___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteList___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int QuoteList___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->NewsList___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int NewsList___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol___(std::string token, std::string Exchange, std::string symbol, ns1__RESPONSE &ns1__RESPONSE_) { return this->NewsListBySymbol___(NULL, NULL, token, Exchange, symbol, ns1__RESPONSE_); }
	virtual	int NewsListBySymbol___(const char *endpoint, const char *soap_action, std::string token, std::string Exchange, std::string symbol, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->FundamentalList___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int FundamentalList___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->TechnicalList___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int TechnicalList___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate___(std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDate___(NULL, NULL, Token, Exchange, QuoteDate, ns1__RESPONSE_); }
	virtual	int QuoteListByDate___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2___(std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDate2___(NULL, NULL, Token, Exchange, QuoteDate, ns1__RESPONSE_); }
	virtual	int QuoteListByDate2___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory___(std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistory___(NULL, NULL, Token, Exchange, Symbol, StartDate, ns1__RESPONSE_); }
	virtual	int SymbolHistory___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->Top10Gains___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int Top10Gains___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->Top10Losses___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int Top10Losses___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolChart___(NULL, NULL, Token, Exchange, Symbol, ns1__RESPONSE_); }
	virtual	int SymbolChart___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->ExchangeMonths___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int ExchangeMonths___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->SplitListByExchange___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int SplitListByExchange___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) { return this->SplitListBySymbol___(NULL, NULL, Token, Exchange, Symbol, ns1__RESPONSE_); }
	virtual	int SplitListBySymbol___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) { return this->CountryList___(NULL, NULL, Token, ns1__RESPONSE_); }
	virtual	int CountryList___(const char *endpoint, const char *soap_action, std::string Token, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod___(std::string Token, std::string Exchange, std::string Symbol, std::string Date, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistoryPeriod___(NULL, NULL, Token, Exchange, Symbol, Date, Period, ns1__RESPONSE_); }
	virtual	int SymbolHistoryPeriod___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, std::string Date, std::string Period, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange___(std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, std::string EndDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolHistoryPeriodByDateRange___(NULL, NULL, Token, Exchange, Symbol, StartDate, EndDate, Period, ns1__RESPONSE_); }
	virtual	int SymbolHistoryPeriodByDateRange___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, std::string EndDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDatePeriod___(NULL, NULL, Token, Exchange, QuoteDate, Period, ns1__RESPONSE_); }
	virtual	int QuoteListByDatePeriod___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) { return this->QuoteListByDatePeriod2___(NULL, NULL, Token, Exchange, QuoteDate, Period, ns1__RESPONSE_); }
	virtual	int QuoteListByDatePeriod2___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) { return this->SymbolChangesByExchange___(NULL, NULL, Token, Exchange, ns1__RESPONSE_); }
	virtual	int SymbolChangesByExchange___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) { return this->DataClientLatestVersion___(NULL, NULL, Token, ns1__RESPONSE_); }
	virtual	int DataClientLatestVersion___(const char *endpoint, const char *soap_action, std::string Token, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) { return this->DataFormats___(NULL, NULL, Token, ns1__RESPONSE_); }
	virtual	int DataFormats___(const char *endpoint, const char *soap_action, std::string Token, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat___(std::string Token, std::string DataFormat, std::string IncludeHeader, std::string IncludeSuffix, ns1__RESPONSE &ns1__RESPONSE_) { return this->UpdateDataFormat___(NULL, NULL, Token, DataFormat, IncludeHeader, IncludeSuffix, ns1__RESPONSE_); }
	virtual	int UpdateDataFormat___(const char *endpoint, const char *soap_action, std::string Token, std::string DataFormat, std::string IncludeHeader, std::string IncludeSuffix, ns1__RESPONSE &ns1__RESPONSE_);

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) { return this->ValidateAccess___(NULL, NULL, Token, Exchange, QuoteDate, Period, ns1__RESPONSE_); }
	virtual	int ValidateAccess___(const char *endpoint, const char *soap_action, std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_);
};

} // namespace ns

#endif
