/* nsDataSoapService.h
   Generated by gSOAP 2.8.28 from eoddatawebservice.h

gSOAP XML Web services tools
Copyright (C) 2000-2016, Robert van Engelen, Genivia Inc. All Rights Reserved.
The soapcpp2 tool and its generated software are released under the GPL.
This program is released under the GPL with the additional exemption that
compiling, linking, and/or using OpenSSL is allowed.
--------------------------------------------------------------------------------
A commercial use license is available from Genivia Inc., contact@genivia.com
--------------------------------------------------------------------------------
*/

#ifndef nsDataSoapService_H
#define nsDataSoapService_H
#include "nsH.h"

namespace ns {
class SOAP_CMAC DataSoapService
{ public:
	struct soap *soap;
	bool soap_own;
	/// Variables globally declared in eoddatawebservice.h (non-static)
	/// Constructor
	DataSoapService();
	/// Copy constructor
	DataSoapService(const DataSoapService&);
	/// Constructor to use/share an engine state
	DataSoapService(struct soap*);
	/// Constructor with engine input+output mode control
	DataSoapService(soap_mode iomode);
	/// Constructor with engine input and output mode control
	DataSoapService(soap_mode imode, soap_mode omode);
	/// Destructor deletes non-shared engine context only (use destroy() to delete deserialized data)
	virtual ~DataSoapService();
	/// Delete all deserialized data (with soap_destroy() and soap_end())
	virtual	void destroy();
	/// Delete all deserialized data and reset to defaults
	virtual	void reset();
	/// Initializer used by constructor
	virtual	void DataSoapService_init(soap_mode imode, soap_mode omode);
	/// Create a new copy
	virtual	DataSoapService *copy() SOAP_PURE_VIRTUAL;
	/// Copy assignment
	DataSoapService& operator=(const DataSoapService&);
	/// Close connection (normally automatic)
	virtual	int soap_close_socket();
	/// Force close connection (can kill a thread blocked on IO)
	virtual	int soap_force_close_socket();
	/// Return sender-related fault to sender
	virtual	int soap_senderfault(const char *string, const char *detailXML);
	/// Return sender-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_senderfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Return receiver-related fault to sender
	virtual	int soap_receiverfault(const char *string, const char *detailXML);
	/// Return receiver-related fault with SOAP 1.2 subcode to sender
	virtual	int soap_receiverfault(const char *subcodeQName, const char *string, const char *detailXML);
	/// Print fault
	virtual	void soap_print_fault(FILE*);
#ifndef WITH_LEAN
	/// Print fault to stream
#ifndef WITH_COMPAT
	virtual	void soap_stream_fault(std::ostream&);
#endif
	/// Put fault into buffer
	virtual	char *soap_sprint_fault(char *buf, size_t len);
#endif
	/// Disables and removes SOAP Header from message
	virtual	void soap_noheader();
	/// Get SOAP Header structure (NULL when absent)
	virtual	const SOAP_ENV__Header *soap_header();
	/// Run simple single-thread (iterative, non-SSL) service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int run(int port);
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Run simple single-thread SSL service on port until a connection error occurs (returns error code or SOAP_OK), use this->bind_flag = SO_REUSEADDR to rebind for a rerun
	virtual	int ssl_run(int port);
#endif
	/// Bind service to port (returns master socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET bind(const char *host, int port, int backlog);
	/// Accept next request (returns socket or SOAP_INVALID_SOCKET)
	virtual	SOAP_SOCKET accept();
#if defined(WITH_OPENSSL) || defined(WITH_GNUTLS)
	/// Then accept SSL handshake, when SSL is used
	virtual	int ssl_accept();
#endif
	/// Serve this request (returns error code or SOAP_OK)
	virtual	int serve();
	/// Used by serve() to dispatch a request (returns error or SOAP_OK)
	virtual	int dispatch();
	virtual	int dispatch(struct soap *soap);

	///
	/// Service operations (you should define these):
	/// Note: compile with -DWITH_PURE_VIRTUAL for pure virtual methods
	///

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2(_ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership(_ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList(_ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet(_ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList(_ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2(_ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet(_ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2(_ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet(_ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList(_ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList(_ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol(_ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList(_ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList(_ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate(_ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2(_ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory(_ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains(_ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses(_ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart(_ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths(_ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange(_ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol(_ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList(_ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod(_ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange(_ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod(_ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2(_ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange(_ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion(_ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats(_ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat(_ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess(_ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login_(_ns1__Login *ns1__Login, _ns1__LoginResponse &ns1__LoginResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2_(_ns1__Login2 *ns1__Login2, _ns1__Login2Response &ns1__Login2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership_(_ns1__Membership *ns1__Membership, _ns1__MembershipResponse &ns1__MembershipResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList_(_ns1__ExchangeList *ns1__ExchangeList, _ns1__ExchangeListResponse &ns1__ExchangeListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet_(_ns1__ExchangeGet *ns1__ExchangeGet, _ns1__ExchangeGetResponse &ns1__ExchangeGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList_(_ns1__SymbolList *ns1__SymbolList, _ns1__SymbolListResponse &ns1__SymbolListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2_(_ns1__SymbolList2 *ns1__SymbolList2, _ns1__SymbolList2Response &ns1__SymbolList2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet_(_ns1__QuoteGet *ns1__QuoteGet, _ns1__QuoteGetResponse &ns1__QuoteGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2_(_ns1__QuoteList2 *ns1__QuoteList2, _ns1__QuoteList2Response &ns1__QuoteList2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet_(_ns1__SymbolGet *ns1__SymbolGet, _ns1__SymbolGetResponse &ns1__SymbolGetResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList_(_ns1__QuoteList *ns1__QuoteList, _ns1__QuoteListResponse &ns1__QuoteListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList_(_ns1__NewsList *ns1__NewsList, _ns1__NewsListResponse &ns1__NewsListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol_(_ns1__NewsListBySymbol *ns1__NewsListBySymbol, _ns1__NewsListBySymbolResponse &ns1__NewsListBySymbolResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList_(_ns1__FundamentalList *ns1__FundamentalList, _ns1__FundamentalListResponse &ns1__FundamentalListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList_(_ns1__TechnicalList *ns1__TechnicalList, _ns1__TechnicalListResponse &ns1__TechnicalListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate_(_ns1__QuoteListByDate *ns1__QuoteListByDate, _ns1__QuoteListByDateResponse &ns1__QuoteListByDateResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2_(_ns1__QuoteListByDate2 *ns1__QuoteListByDate2, _ns1__QuoteListByDate2Response &ns1__QuoteListByDate2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory_(_ns1__SymbolHistory *ns1__SymbolHistory, _ns1__SymbolHistoryResponse &ns1__SymbolHistoryResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains_(_ns1__Top10Gains *ns1__Top10Gains, _ns1__Top10GainsResponse &ns1__Top10GainsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses_(_ns1__Top10Losses *ns1__Top10Losses, _ns1__Top10LossesResponse &ns1__Top10LossesResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart_(_ns1__SymbolChart *ns1__SymbolChart, _ns1__SymbolChartResponse &ns1__SymbolChartResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths_(_ns1__ExchangeMonths *ns1__ExchangeMonths, _ns1__ExchangeMonthsResponse &ns1__ExchangeMonthsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange_(_ns1__SplitListByExchange *ns1__SplitListByExchange, _ns1__SplitListByExchangeResponse &ns1__SplitListByExchangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol_(_ns1__SplitListBySymbol *ns1__SplitListBySymbol, _ns1__SplitListBySymbolResponse &ns1__SplitListBySymbolResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList_(_ns1__CountryList *ns1__CountryList, _ns1__CountryListResponse &ns1__CountryListResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod_(_ns1__SymbolHistoryPeriod *ns1__SymbolHistoryPeriod, _ns1__SymbolHistoryPeriodResponse &ns1__SymbolHistoryPeriodResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange_(_ns1__SymbolHistoryPeriodByDateRange *ns1__SymbolHistoryPeriodByDateRange, _ns1__SymbolHistoryPeriodByDateRangeResponse &ns1__SymbolHistoryPeriodByDateRangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod_(_ns1__QuoteListByDatePeriod *ns1__QuoteListByDatePeriod, _ns1__QuoteListByDatePeriodResponse &ns1__QuoteListByDatePeriodResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2_(_ns1__QuoteListByDatePeriod2 *ns1__QuoteListByDatePeriod2, _ns1__QuoteListByDatePeriod2Response &ns1__QuoteListByDatePeriod2Response) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange_(_ns1__SymbolChangesByExchange *ns1__SymbolChangesByExchange, _ns1__SymbolChangesByExchangeResponse &ns1__SymbolChangesByExchangeResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion_(_ns1__DataClientLatestVersion *ns1__DataClientLatestVersion, _ns1__DataClientLatestVersionResponse &ns1__DataClientLatestVersionResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats_(_ns1__DataFormats *ns1__DataFormats, _ns1__DataFormatsResponse &ns1__DataFormatsResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat_(_ns1__UpdateDataFormat *ns1__UpdateDataFormat, _ns1__UpdateDataFormatResponse &ns1__UpdateDataFormatResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess_(_ns1__ValidateAccess *ns1__ValidateAccess, _ns1__ValidateAccessResponse &ns1__ValidateAccessResponse) SOAP_PURE_VIRTUAL;

	/// Web service operation 'LoginResponse' (returns error code or SOAP_OK)
	virtual	int LoginResponse__(ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login2Response' (returns error code or SOAP_OK)
	virtual	int Login2Response__(ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'MembershipResponse' (returns error code or SOAP_OK)
	virtual	int MembershipResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeListResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeGetResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolListResponse' (returns error code or SOAP_OK)
	virtual	int SymbolListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList2Response' (returns error code or SOAP_OK)
	virtual	int SymbolList2Response__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteGetResponse' (returns error code or SOAP_OK)
	virtual	int QuoteGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList2Response' (returns error code or SOAP_OK)
	virtual	int QuoteList2Response__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolGetResponse' (returns error code or SOAP_OK)
	virtual	int SymbolGetResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsListResponse' (returns error code or SOAP_OK)
	virtual	int NewsListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsListBySymbolResponse' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbolResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'FundamentalListResponse' (returns error code or SOAP_OK)
	virtual	int FundamentalListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'TechnicalListResponse' (returns error code or SOAP_OK)
	virtual	int TechnicalListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDateResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListByDateResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate2Response' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2Response__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10GainsResponse' (returns error code or SOAP_OK)
	virtual	int Top10GainsResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10LossesResponse' (returns error code or SOAP_OK)
	virtual	int Top10LossesResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChartResponse' (returns error code or SOAP_OK)
	virtual	int SymbolChartResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeMonthsResponse' (returns error code or SOAP_OK)
	virtual	int ExchangeMonthsResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListByExchangeResponse' (returns error code or SOAP_OK)
	virtual	int SplitListByExchangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListBySymbolResponse' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbolResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CountryListResponse' (returns error code or SOAP_OK)
	virtual	int CountryListResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriodResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriodByDateRangeResponse' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriodResponse' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriodResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod2Response' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2Response__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChangesByExchangeResponse' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchangeResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataClientLatestVersionResponse' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersionResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataFormatsResponse' (returns error code or SOAP_OK)
	virtual	int DataFormatsResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'UpdateDataFormatResponse' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormatResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ValidateAccessResponse' (returns error code or SOAP_OK)
	virtual	int ValidateAccessResponse__(ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login' (returns error code or SOAP_OK)
	virtual	int Login___(std::string Username, std::string Password, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Login2' (returns error code or SOAP_OK)
	virtual	int Login2___(std::string Username, std::string Password, std::string Version, ns1__LOGINRESPONSE &ns1__LOGINRESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Membership' (returns error code or SOAP_OK)
	virtual	int Membership___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeList' (returns error code or SOAP_OK)
	virtual	int ExchangeList___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeGet' (returns error code or SOAP_OK)
	virtual	int ExchangeGet___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList' (returns error code or SOAP_OK)
	virtual	int SymbolList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolList2' (returns error code or SOAP_OK)
	virtual	int SymbolList2___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteGet' (returns error code or SOAP_OK)
	virtual	int QuoteGet___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList2' (returns error code or SOAP_OK)
	virtual	int QuoteList2___(std::string Token, std::string Exchange, std::string Symbols, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolGet' (returns error code or SOAP_OK)
	virtual	int SymbolGet___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteList' (returns error code or SOAP_OK)
	virtual	int QuoteList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsList' (returns error code or SOAP_OK)
	virtual	int NewsList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'NewsListBySymbol' (returns error code or SOAP_OK)
	virtual	int NewsListBySymbol___(std::string token, std::string Exchange, std::string symbol, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'FundamentalList' (returns error code or SOAP_OK)
	virtual	int FundamentalList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'TechnicalList' (returns error code or SOAP_OK)
	virtual	int TechnicalList___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate___(std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDate2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDate2___(std::string Token, std::string Exchange, std::string QuoteDate, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistory' (returns error code or SOAP_OK)
	virtual	int SymbolHistory___(std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Gains' (returns error code or SOAP_OK)
	virtual	int Top10Gains___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'Top10Losses' (returns error code or SOAP_OK)
	virtual	int Top10Losses___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChart' (returns error code or SOAP_OK)
	virtual	int SymbolChart___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ExchangeMonths' (returns error code or SOAP_OK)
	virtual	int ExchangeMonths___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListByExchange' (returns error code or SOAP_OK)
	virtual	int SplitListByExchange___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SplitListBySymbol' (returns error code or SOAP_OK)
	virtual	int SplitListBySymbol___(std::string Token, std::string Exchange, std::string Symbol, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'CountryList' (returns error code or SOAP_OK)
	virtual	int CountryList___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriod' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriod___(std::string Token, std::string Exchange, std::string Symbol, std::string Date, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolHistoryPeriodByDateRange' (returns error code or SOAP_OK)
	virtual	int SymbolHistoryPeriodByDateRange___(std::string Token, std::string Exchange, std::string Symbol, std::string StartDate, std::string EndDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'QuoteListByDatePeriod2' (returns error code or SOAP_OK)
	virtual	int QuoteListByDatePeriod2___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'SymbolChangesByExchange' (returns error code or SOAP_OK)
	virtual	int SymbolChangesByExchange___(std::string Token, std::string Exchange, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataClientLatestVersion' (returns error code or SOAP_OK)
	virtual	int DataClientLatestVersion___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'DataFormats' (returns error code or SOAP_OK)
	virtual	int DataFormats___(std::string Token, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'UpdateDataFormat' (returns error code or SOAP_OK)
	virtual	int UpdateDataFormat___(std::string Token, std::string DataFormat, std::string IncludeHeader, std::string IncludeSuffix, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;

	/// Web service operation 'ValidateAccess' (returns error code or SOAP_OK)
	virtual	int ValidateAccess___(std::string Token, std::string Exchange, std::string QuoteDate, std::string Period, ns1__RESPONSE &ns1__RESPONSE_) SOAP_PURE_VIRTUAL;
};

} // namespace ns

#endif
